# Generated by Django 4.2.6 on 2023-12-01 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steam',
            fields=[
                ('idgamesteam', models.OneToOneField(db_column='IDGameSteam', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='shop.game')),
                ('gamename', models.CharField(blank=True, db_column='GameName', max_length=45, null=True)),
                ('gameprice', models.FloatField(blank=True, db_column='GamePrice', null=True)),
            ],
            options={
                'verbose_name_plural': 'Steam',
                'db_table': 'steam',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'managed': False, 'verbose_name_plural': 'Game'},
        ),
        migrations.AlterModelOptions(
            name='gamegenre',
            options={'managed': False, 'verbose_name_plural': 'GameGenre'},
        ),
        migrations.AlterModelOptions(
            name='gamelauncher',
            options={'managed': False, 'verbose_name_plural': 'GameLauncher'},
        ),
    ]
