# Generated by Django 4.2.6 on 2023-12-01 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_steam_alter_game_options_alter_gamegenre_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epicgames',
            fields=[
                ('idgameepicgames', models.OneToOneField(db_column='IDGameEpicGames', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='shop.game')),
                ('gamename', models.CharField(blank=True, db_column='GameName', max_length=45, null=True)),
                ('gameprice', models.FloatField(blank=True, db_column='GamePrice', null=True)),
            ],
            options={
                'verbose_name_plural': 'EpicGames',
                'db_table': 'epicgames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gog',
            fields=[
                ('idgamegog', models.OneToOneField(db_column='IDGameGOG', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='shop.game')),
                ('gamename', models.CharField(blank=True, db_column='GameName', max_length=45, null=True)),
                ('gameprice', models.FloatField(blank=True, db_column='GamePrice', null=True)),
            ],
            options={
                'verbose_name_plural': 'GOG',
                'db_table': 'gog',
                'managed': False,
            },
        ),
    ]
